In [2]:
import numpy as np
b=np.array([(1,2,3),(7,8,9),(13,14,15),(19,20,21)])
print(b)

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]


In [11]:
import sys
S=range(1000)
print(sys.getsizeof(S)*len(S))

D=np.arange(1000)
print(D.size*D.itemsize)

import time
SIZE= 1000000
L1=range(SIZE)
L2=range(SIZE)
A1=np.arange(SIZE)
A2=np.arange(SIZE)


48000
8000


In [16]:
start=time.time()
result=[(x,y) for x, y in zip(L1,L2)]
print((time.time()-start)*1000)

start=time.time()
result=A1+A2
print((time.time()-start)*1000)

128.4654140472412
30.619382858276367


In [17]:
import time 

In [18]:
import numpy as np

In [19]:
list1=[i for i in range(10000)]

In [20]:
list2=[i for i in range(10000)]

In [21]:
inicio=time.time()


In [22]:
dot=0

In [23]:
for i,j in zip(list1, list2):
    dot+=i*j

In [24]:
round(time.time()-inicio,5)


1.11198

In [ ]:
import time

In [ ]:
import numpy as np

In [27]:
arr1=np.array([i for i in range(10000)])
              

In [38]:
arr2=np.array([i for i in range(10000)])


In [39]:
inicio=time.time()


In [40]:
arr=np.concatenate((arr1,arr2),axis=0)


In [41]:
round(time.time()-inicio,5)

27.04791

In [47]:
lista=[25,12,15,66,12.5]
vector=np.array(lista)
print(vector)

[25.  12.  15.  66.  12.5]


In [48]:
print(vector[1:])


[12.  15.  66.  12.5]


In [49]:
print(vector[:4])


[25. 12. 15. 66.]


In [50]:
print("-vector original")


-vector original


In [51]:
print(vector)

[25.  12.  15.  66.  12.5]


In [53]:
print("-sumarle 1 a cada elemento del vector")
print(vector +1)

-sumarle 1 a cada elemento del vector
[26.  13.  16.  67.  13.5]


In [54]:
print("- multiplicar por 5 cada elemento del vector")
print(vector*5)

- multiplicar por 5 cada elemento del vector
[125.   60.   75.  330.   62.5]


In [55]:
print("-suma de los elementos")
print(np.mean(vector))

-suma de los elementos
26.1


In [56]:
print("- el vector sumado a si mismo")

- el vector sumado a si mismo


In [57]:
print(vector+vector)

[ 50.  24.  30. 132.  25.]


In [58]:
print("Suma de vectores vector1 y vector2(mismo tamaño)")
vector2=np.array([11,55,1.2,7.6,-8])
print(vector+vector2)


Suma de vectores vector1 y vector2(mismo tamaño)
[36.  67.  16.2 73.6  4.5]


In [59]:
print("- Matriz creada con una lista de listas")
lista_de_listas=[[1,-4],[12,3],[7.2,5]]


- Matriz creada con una lista de listas


In [60]:
matriz=np.array(lista_de_listas)
print(matriz)


[[ 1.  -4. ]
 [12.   3. ]
 [ 7.2  5. ]]


In [61]:
print("- Matriz creada con np.zeros")
dimensiones=(2,3)
matriz_ceros=np.zeros(dimensiones)
print(matriz_ceros)

- Matriz creada con np.zeros
[[0. 0. 0.]
 [0. 0. 0.]]


In [62]:
print("- Matriz creada con np.ones")
dimensiones=(3,2)
matriz_unos=np.ones(dimensiones)
print(matriz_unos)

- Matriz creada con np.ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [63]:
print("- Copia de la matriz crwada con np ones")
matriz_unos_copia=np.copy(matriz_unos)
print(matriz_unos_copia)
      

- Copia de la matriz crwada con np ones
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [70]:
#ejercicio
#Una clase de 20 estudiantes rindió un examen sobre 20 puntos. Se tienen las notas almacenadas en un arreglo de NumPy.
#1. Genera un arreglo de 20 notas aleatorias entre 0 y 20.
#2. Calcula:
#• La nota promedio.
#• La nota más alta y la más baja.
#• Cuántos estudiantes aprobaron (nota ≥ 14).
#3. Ordena las notas de menor a mayor.
#4. Escala las notas para que estén en rango de 0 a 10.

In [88]:
#Generar las calificaciones
notas=np.random.randint(0,21,300)

In [89]:
notas

array([ 1,  0, 20, 19,  7, 10,  4, 12,  3,  3, 14, 14,  8, 16, 18,  6,  6,
       13, 17, 10, 20,  8,  0, 11, 17, 18, 19,  0,  7,  4, 20,  1,  0,  5,
       10,  9, 10, 11,  0, 12, 17, 16,  5, 14,  8, 16,  9, 19,  4,  2,  0,
       11, 10, 20, 13, 12, 20,  3,  9,  1,  9,  2,  3, 12,  8,  4, 15,  2,
       13, 20,  6, 10, 13,  7,  3, 14,  5, 20,  5, 14, 16, 14, 13, 14, 19,
       17,  2,  4, 12, 14,  7,  1,  4,  7,  1, 11,  3,  7,  5, 20, 17, 15,
       11,  7, 16,  5, 19, 16,  5,  3, 20, 15,  9, 13, 15,  9, 12,  6,  8,
       12, 10, 18, 16,  9, 13,  5,  6, 16,  1, 14,  6,  3, 14, 14,  6,  4,
       11,  2,  8, 12,  5, 17, 11,  0,  7, 14, 14,  6,  2, 18, 10,  3,  6,
        0,  0, 10,  1,  1,  2,  8,  5,  3,  4, 17, 15,  2, 17,  9, 18, 15,
       16,  9,  2, 15,  3,  0,  7, 19,  8,  8, 11, 14, 17,  5, 14,  0, 10,
       18,  8,  2, 17, 12,  8, 18,  0, 18,  8, 17,  8, 20,  8, 10, 17, 11,
        0,  2, 11, 19,  3,  7,  1, 16,  2, 14,  3,  5,  5, 11, 19, 13,  0,
        7, 19, 13, 19,  2

In [90]:
#Estadisticos

In [91]:
print("Promedio")
np.mean(notas)

Promedio


np.float64(9.7)

In [92]:
print("Nota mas alta")
np.max(notas)

Nota mas alta


np.int32(20)

In [93]:
print("Nota mas baja")
np.min(notas)

Nota mas baja


np.int32(0)

In [94]:
print("Aprobados")
np.sum(notas>=14)

Aprobados


np.int64(95)

In [95]:
#calificaciones ordenadas

In [96]:
notas_ordenadas=np.sort(notas)

In [97]:
notas_ordenadas

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,
        8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,
        9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11,
       11, 11, 11, 11, 11, 11, 11, 11, 11, 12, 12, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
       13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14

In [98]:
#en escala de 0 a 10

In [99]:
notas_escala=(notas/20)*10

In [100]:
notas_escala

array([ 0.5,  0. , 10. ,  9.5,  3.5,  5. ,  2. ,  6. ,  1.5,  1.5,  7. ,
        7. ,  4. ,  8. ,  9. ,  3. ,  3. ,  6.5,  8.5,  5. , 10. ,  4. ,
        0. ,  5.5,  8.5,  9. ,  9.5,  0. ,  3.5,  2. , 10. ,  0.5,  0. ,
        2.5,  5. ,  4.5,  5. ,  5.5,  0. ,  6. ,  8.5,  8. ,  2.5,  7. ,
        4. ,  8. ,  4.5,  9.5,  2. ,  1. ,  0. ,  5.5,  5. , 10. ,  6.5,
        6. , 10. ,  1.5,  4.5,  0.5,  4.5,  1. ,  1.5,  6. ,  4. ,  2. ,
        7.5,  1. ,  6.5, 10. ,  3. ,  5. ,  6.5,  3.5,  1.5,  7. ,  2.5,
       10. ,  2.5,  7. ,  8. ,  7. ,  6.5,  7. ,  9.5,  8.5,  1. ,  2. ,
        6. ,  7. ,  3.5,  0.5,  2. ,  3.5,  0.5,  5.5,  1.5,  3.5,  2.5,
       10. ,  8.5,  7.5,  5.5,  3.5,  8. ,  2.5,  9.5,  8. ,  2.5,  1.5,
       10. ,  7.5,  4.5,  6.5,  7.5,  4.5,  6. ,  3. ,  4. ,  6. ,  5. ,
        9. ,  8. ,  4.5,  6.5,  2.5,  3. ,  8. ,  0.5,  7. ,  3. ,  1.5,
        7. ,  7. ,  3. ,  2. ,  5.5,  1. ,  4. ,  6. ,  2.5,  8.5,  5.5,
        0. ,  3.5,  7. ,  7. ,  3. ,  1. ,  9. ,  5

In [101]:
np.random.rand(3,2)

array([[0.25857776, 0.02355986],
       [0.62306555, 0.4258248 ],
       [0.21073662, 0.97473654]])

In [102]:
np.random.rand(10,10)

array([[0.60647504, 0.6201595 , 0.79540722, 0.89689649, 0.79551793,
        0.48341826, 0.36926414, 0.16164896, 0.74353862, 0.95089185],
       [0.21861191, 0.32363239, 0.33578776, 0.716578  , 0.86111151,
        0.58734582, 0.73626272, 0.10656258, 0.62982856, 0.94496171],
       [0.4880706 , 0.38121122, 0.46974825, 0.27109025, 0.85042185,
        0.03091821, 0.94897455, 0.36817721, 0.73924043, 0.43490938],
       [0.01161752, 0.0063619 , 0.6568296 , 0.25606344, 0.10184991,
        0.27039578, 0.25233844, 0.70690793, 0.8609787 , 0.55449753],
       [0.33149857, 0.00651662, 0.55309432, 0.76671439, 0.20737464,
        0.44708102, 0.3795529 , 0.54544012, 0.22503547, 0.36366572],
       [0.36896917, 0.89097981, 0.02912012, 0.5774695 , 0.85417427,
        0.31673711, 0.71945847, 0.6172245 , 0.93838654, 0.03294556],
       [0.76023888, 0.45803675, 0.5648906 , 0.8826986 , 0.17303924,
        0.85170384, 0.67203606, 0.93866857, 0.57394711, 0.36779928],
       [0.497485  , 0.32267887, 0.4469962

In [ ]:
#Crear un vector con valores dentro del rango 10 a 49
a=np