### Instalación:
 pip install numpy

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


### importar libreria
 import numpy as np

 el as np nos dice como llmaremos a la libreria cuando la requira


In [4]:
import numpy as np

### Podemos practicar transformaciones de arrays 

In [5]:
lista1 = np.array([1,2,3])
lista2 = [1,2,3]
print("Transforme la lista 1 a un array ", lista1, "\nTenemos una lista dos que sigue siendo una lista ", lista2)

Transforme la lista 1 a un array  [1 2 3] 
Tenemos una lista dos que sigue siendo una lista  [1, 2, 3]


### LISTAS A TUPLAS
Dejamos de usar listas y usamos tuplas ya que estas nos permiten tener mayor
mutabilidad(No se pueden cambiar una vez creadas) y velocidad.
Descpues de usar np.array() son los mismo a la final. La elección es 
solo una cuestión de si quieres usar una fuente de datos mutable o inmutable 
antes de la conversión. Llamado ndarray.

In [6]:
Matriz1 = [[1,2,3],[4,5,6],[7,8,9]]
print("Imprimimos una matriz de listas", Matriz1)

Imprimimos una matriz de listas [[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [7]:
Matriz2 = [(1,2,3),(4,5,6),(7,8,9)]
print("Imprimimos una Matriz de tuplas", Matriz2)

Imprimimos una Matriz de tuplas [(1, 2, 3), (4, 5, 6), (7, 8, 9)]


In [8]:
Matriz1_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Transformamos la matriz 1 en un array \n", Matriz1_array)

Transformamos la matriz 1 en un array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
Matriz2_array = np.array([(1,2,3),(4,5,6),(7,8,9)])
print("Transformamos la matriz 2 en un array \n", Matriz2_array)

Transformamos la matriz 2 en un array 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Creamos un array 3D: 2 "capas" o matrices, cada una de 3x3.
array_3d = np.array([
    # Capa 1 (Matriz 1)
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],
    
    # Capa 2 (Matriz 2)
    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])
print("Por favor crear un arreglo de 3 dimensiones\n", array_3d)

Por favor crear un arreglo de 3 dimensiones
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]


### 1. Enfoque de Python Nativo (Variable S)



* import sys: Importa el módulo sys, que nos permite interactuar con el entorno del sistema, incluyendo funciones para obtener el tamaño de los objetos.

S = range(1000): Crea un objeto range de Python con 1000 números (del 0 al 999).

* sys.getsizeof(5): Esta función obtiene el tamaño en bytes de un objeto entero simple (el número 5, o cualquier entero pequeño). En Python, cada elemento de una lista es un objeto completo con su propia estructura de datos, lo que consume mucha memoria.

* len(S): Multiplica el tamaño de ese objeto entero por la cantidad de elementos (1000).


In [11]:
import sys
S = range(1000)
print(sys.getsizeof(5)*len(S))

28000


* El Resultado (28000 bytes): Este cálculo estima el espacio total. La cifra alta (28000 en la diapositiva) se debe a que la lista de Python almacena referencias dispersas a objetos, haciendo que la lista sea muy ineficiente en memoria.

### 2. Enfoque de NumPy (Variable D)

* D = np.arange(1000): Crea un array de NumPy (vector) con 1000 números. Este array está optimizado para almacenar los datos en un bloque contiguo de memoria.

* D.size: Esta es una propiedad del array que devuelve la cantidad total de elementos (1000).

* D.itemsize: Esta propiedad devuelve el tamaño en bytes que ocupa cada elemento de forma uniforme (por ejemplo, 8 bytes si son enteros de 64 bits).

In [12]:
D = np.arange(1000) 
print(D.size*D.itemsize)

8000


* El Resultado (8000 bytes): El cálculo es el número de elementos por el tamaño de cada elemento, y el resultado es drásticamente menor (8000 en la diapositiva).

### VELOCIDAD
* Para explicar y comparar velocidades entre algo normal de phyton y Numpy vamos a decladad un arreglo el cual será leido en un tiempo determinado 

In [13]:
import time ##importamos la biblioteca que nnos permitira medir el tiempo
SIZE = 1000000  #Asignamos una variable con uncierto tamaño de elementos

* Ahora declaramos variables las cuales utilizaremos para manipular esta variable que nos ayudara a medir y diferenciar los tiempos al momento de realizar una misma actividad

In [14]:
L1= range(SIZE) 
L2= range(SIZE)
A1= np.arange(SIZE) 
A2= np.arange(SIZE)
#print(L1)
#print(A1)

* Vamos a verificar el tiempo que tarda en operar con PHYTON


In [15]:
start= time.time()
result=[(x + y) for x,y in zip(L1,L2)] # Revisar Comprehension
print((time.time()-start)*1000, " Milisegundos")
#print(result)

122.21813201904297  Milisegundos


* Ahora el tiempo que tarda con NumPy

In [16]:
start=time.time()
result= A1+A2
print((time.time()-start)*1000, " Milisegundos")
#print(result)

15.755176544189453  Milisegundos


#### Otros ejemplos de tiempo:

In [17]:
list1=[i for i in range (10)]
list2=[i for i in range (10)]
print("Lista 1 creado directamente  ", list1)
print("Lista 1 creado directamente  ", list2)
inicio = time.time()
dot=0
for i,j in zip (list1, list2):
  dot+=i*j
print("Tiempo que tardó: ", round(((time.time()-inicio) * 1000),5), " Milisegundos")
print("Resultado de la Operacion: ", dot)

Lista 1 creado directamente   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Lista 1 creado directamente   [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Tiempo que tardó:  0.16642  Milisegundos
Resultado de la Operacion:  285


In [18]:
import time
import numpy as np
arr1=np.array([i for i in range(10)])
arr2=np.array([i for i in range(10)])
print("Lista 1 creado directamente  ", arr1)
print("Lista 1 creado directamente  ", arr2)
inicio = time.time()
arr=np.dot(arr1, arr2)
round(time.time()-inicio,5)
print("Tiempo que tardó: ", round(((time.time()-inicio) * 1000),5), " Milisegundos")
print("Resultado de la Operacion: ", arr)

Lista 1 creado directamente   [0 1 2 3 4 5 6 7 8 9]
Lista 1 creado directamente   [0 1 2 3 4 5 6 7 8 9]
Tiempo que tardó:  0.29039  Milisegundos
Resultado de la Operacion:  285


##### Concatenación de dos arreglos:


In [19]:

 list1=[i for i in range (10000)]
 list2=[i for i in range (10000)]
 inicio = time.time()
 list1+=list2
 round(time.time()-inicio,5)

0.0002

In [20]:
 arr1=np.array([i for i in range(10000)])
 arr2=np.array([i for i in range(10000)])
 inicio = time.time()
 arr=np.concatenate((arr1,arr2),axis=0)
 round(time.time()-inicio,5)

0.00019

##### Eliminación:

In [21]:

 list1=[i for i in range (10000)]
 inicio = time.time()
 del(list1)
 round(time.time()-inicio,5)

0.00023

In [22]:
 arr1=np.array([i for i in range(10000)])
 inicio = time.time()
 del(arr1)
 round(time.time()-inicio,5)

9e-05

## Ejercicios VECTOR

* Al ser el elemento vector de numpy, nos permite realizar operaciones de forma simple


In [23]:
lista=[25,12,15,66,12] 
vector=np.array(lista) 
print(vector)

[25 12 15 66 12]


*  Podemos acceder a sub elementos del vector:

In [24]:
print(vector[3])
print(vector[1:4])
print(vector[1:])
print(vector[:4])
print(vector[:])

66
[12 15 66]
[12 15 66 12]
[25 12 15 66]
[25 12 15 66 12]


* Vector original

In [25]:
print(vector)

[25 12 15 66 12]


* Sumarle 1 a cada elemento del vector:

In [26]:
print(vector+1)

[26 13 16 67 13]


* Multiplicar por 5 cada elemento del vector:

In [27]:
print(vector*5)

[125  60  75 330  60]


* Suma de los elementos:

In [28]:
print(np.sum(vector))

130


* Promedio (media) de los elementos:

In [29]:
print(np.mean(vector)) 

26.0


* El vector sumado a si mismo:

In [30]:
print(vector+vector)

[ 50  24  30 132  24]


* Suma de vectores vector1 y vector2 (mismo tamaño):

In [31]:
vector2=np.array([11,55,1,7,-8])
print(vector+vector2)

[36 67 16 73  4]


### MATRICES

* Matriz creada con una lista de listas

In [32]:
lista_de_listas=[ [1  ,-4], 
[12 , 3], 
[7, 5]]
print(lista_de_listas)

[[1, -4], [12, 3], [7, 5]]


* Misma Matriz aplicada NumPy

In [33]:
 matriz = np.array(lista_de_listas)
 print(matriz)

[[ 1 -4]
 [12  3]
 [ 7  5]]


* Matriz creada con np.zeros:

In [34]:
dimensiones=(2,3)
matriz_ceros= np.zeros(dimensiones)
print(matriz_ceros)

[[0. 0. 0.]
 [0. 0. 0.]]


* Matriz creada con np.ones:

In [35]:
dimensiones=(3,2)
matriz_unos= np.ones(dimensiones)
print(matriz_unos)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


*  También podemos usar np.copypara copiar una matriz

In [36]:
print("-Copia de la matriz creada con np.ones:")
matriz_unos_copia=np.copy(matriz_unos)
print(matriz_unos_copia)

-Copia de la matriz creada con np.ones:
[[1. 1.]
 [1. 1.]
 [1. 1.]]


* Utilizar numeros randoms para crear una matriz

In [37]:
np.random.rand(3,3)

array([[0.08565805, 0.5901395 , 0.09313438],
       [0.69309203, 0.04280392, 0.19814275],
       [0.90980114, 0.96078048, 0.17315172]])

#### Ejercicios Practicos

* Crear una matriz de 4x4 con valores de 0.5

In [38]:
dim = (4,4)
M1 = np.array(np.ones(dim))
print(M1/2)

[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


*  Crear una matriz de 5x5 con valores al azar

In [39]:
import random
matriz_azar = np.random.randint(1, 101, size=(5, 5))
print(matriz_azar)

[[87 75 31 87 81]
 [35  2 47 29 33]
 [61 45 35 89 83]
 [73 44 49 98 79]
 [85 24 87 78 55]]


* Crear un vector con valores dentro del rango 10 a 49

In [40]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


* Invertir el vector

In [ ]:
print(a[::-2])


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]
