In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [18]:
import numpy as np

In [19]:
a = np.array([([1,2,3],[7,8,9],[13,14,15], [19,20,21])])

In [20]:
print(a)

[[[ 1  2  3]
  [ 7  8  9]
  [13 14 15]
  [19 20 21]]]


In [21]:
import sys

In [22]:
s = range(1000)
print(sys.getsizeof(s) * len(s))

48000


In [25]:
d = np.arange(1000)
print(d.size*d.itemsize)

8000


In [26]:
import time

In [27]:
SIZE = 1000000

In [28]:
L1 = range(SIZE)

In [37]:
L2 = range(SIZE)

In [38]:
A1 = np.arange(SIZE)

In [39]:
A2 = np.arange(SIZE)

In [40]:
start = time.time()
result = [(x,y) for x,y in zip (L1,L2)]
print((time.time() - start ) * 1000)

149.69468116760254


In [49]:
start = time.time()
result = A1 + A2
print((time.time() - start ) * 1000)

3.587961196899414


In [50]:
list1 = [i for i in range(1000)]

In [51]:
list2 = [i for i in range(1000)] 

In [52]:
inicio = time.time()

In [53]:
dot = 0

In [55]:
for i,j in zip (list1, list2):
    dot += i*j
round(time.time() - inicio,5)

14.11578

In [57]:
arr1 = np.array([i for i in range(1000)])

In [62]:
arr2 = np.array([i for i in range(1000)])

In [63]:
inicio = time.time()

In [64]:
arr = np.dot(arr1,arr2)

In [65]:
round(time.time() - inicio,5)

8.45431

In [66]:
arr = np.concatenate((arr1,arr2), axis = 0)

In [67]:
round(time.time() - inicio,5)

157.03822

In [70]:
inicio = time.time()

In [71]:
list1 += list2

In [72]:
round(time.time() - inicio,5)

0.63002

In [73]:
a = np.arange(10,50)

In [74]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [75]:
#Crear un vectpr dentro del rango 10 a 49
a = np.arange(10,50)

In [76]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [77]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [78]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [79]:
r= np.random.random((3,3,3))

In [80]:
r

array([[[0.2859417 , 0.76532375, 0.43730606],
        [0.17625666, 0.83506242, 0.07819927],
        [0.59318558, 0.37320634, 0.61847079]],

       [[0.06934794, 0.06227804, 0.45167613],
        [0.6327248 , 0.37973195, 0.44592022],
        [0.7024074 , 0.9476408 , 0.26836147]],

       [[0.90523792, 0.02864427, 0.48987948],
        [0.90908291, 0.1032582 , 0.1318976 ],
        [0.34913109, 0.20774424, 0.7794485 ]]])

In [81]:
print(r.argmax())
print(r.ravel()[r.argmax()])

16
0.9476407954074229


In [82]:
print(r)

[[[0.2859417  0.76532375 0.43730606]
  [0.17625666 0.83506242 0.07819927]
  [0.59318558 0.37320634 0.61847079]]

 [[0.06934794 0.06227804 0.45167613]
  [0.6327248  0.37973195 0.44592022]
  [0.7024074  0.9476408  0.26836147]]

 [[0.90523792 0.02864427 0.48987948]
  [0.90908291 0.1032582  0.1318976 ]
  [0.34913109 0.20774424 0.7794485 ]]]


In [83]:
print(np.unravel_index(r.argmax(),r.shape))
r[np.unravel_index(r.argmax(), r.shape)]

(np.int64(1), np.int64(2), np.int64(1))


np.float64(0.9476407954074229)

In [ ]:
#Crear matriz de 10 * 10